import { createEmptyRecipe } from '@/lib/recipe/defaults';
import crescenzaKeepNote from '@/Keep/Crescenza Dal Thread Del Forum.json';
import farinataKeepNote from '@/Keep/Farinata.json';
import flavouredPopcornKeepNote from '@/Keep/Flavoured popcorn.json';
import focacciaKeepNote from '@/Keep/Focaccia Genovese Davide Zambelli.json';
import gypsyTartKeepNote from '@/Keep/Gypsy Tart Fallow.json';
import marbleCakeKeepNote from '@/Keep/Marble cake - marmor kuchen_.json';
import pastelKeepNote from '@/Keep/Pastel de Nata.json';
import sbrisolonaKeepNote from '@/Keep/Sbrisolona_.json';
import type { Recipe } from '@/lib/recipe/schema';

interface KeepNoteExport {
  textContent: string;
}

function originalKeepText(note: KeepNoteExport): string {
  return note.textContent.trim();
}

function keepRecipe(overrides: Partial<Recipe> & Pick<Recipe, 'id' | 'title'>): Recipe {
  const recipe = createEmptyRecipe();
  const now = new Date().toISOString();

  return {
    ...recipe,
    ...overrides,
    image: {
      ...recipe.image,
      ...overrides.image,
    },
    source: {
      ...recipe.source,
      type: 'import',
      name: overrides.source?.name ?? 'Google Keep',
      url: overrides.source?.url ?? null,
      author: overrides.source?.author ?? null,
      publishedAt: overrides.source?.publishedAt ?? null,
      accessedAt: overrides.source?.accessedAt ?? now,
    },
    servings: {
      ...recipe.servings,
      ...overrides.servings,
    },
    times: {
      ...recipe.times,
      ...overrides.times,
    },
    classification: {
      ...recipe.classification,
      tags: ['google keep', 'ricette', ...(overrides.classification?.tags ?? [])],
      ...overrides.classification,
    },
    personal: {
      ...recipe.personal,
      ...overrides.personal,
    },
    markdown: {
      ...recipe.markdown,
      ...overrides.markdown,
    },
    createdAt: overrides.createdAt ?? now,
    updatedAt: overrides.updatedAt ?? now,
  };
}

export const keepRecipeSeedRecipes: Recipe[] = [
  keepRecipe({
    id: 'keep-flavoured-popcorn',
    title: 'Popcorn aromatizzato e toffee',
    description: 'Popcorn dolci rivestiti di zucchero per far aderire spezie come cannella, curry o tandoori, piu una variante al caramello leggero con bicarbonato.',
    source: {
      type: 'import',
      name: 'Google Keep: Flavoured popcorn',
      url: null,
      author: null,
      publishedAt: null,
      accessedAt: '2026-05-08T00:00:00.000Z',
    },
    servings: { quantity: 4, unit: 'porzioni', note: 'La variante toffee serve 6 persone.' },
    times: { prepMinutes: 10, cookMinutes: 10, restMinutes: null, totalMinutes: 20 },
    ingredients: [
      { group: 'Popcorn aromatizzato', quantity: '50', unit: 'g', item: 'olio di arachide o vinaccioli', note: null, originalText: '50 g groundnut or grapeseed oil' },
      { group: 'Popcorn aromatizzato', quantity: '115', unit: 'g', item: 'zucchero semolato bianco', note: null, originalText: '115 g white caster sugar' },
      { group: 'Popcorn aromatizzato', quantity: '130', unit: 'g', item: 'mais per popcorn', note: null, originalText: '130 g popcorn kernels' },
      { group: 'Aroma cannella', quantity: '1', unit: 'tbsp', item: 'cannella macinata', note: null, originalText: '1 tbsp ground cinnamon' },
      { group: 'Aroma cannella', quantity: '50', unit: 'g', item: 'zucchero semolato bianco', note: null, originalText: '50 g white caster sugar' },
      { group: 'Aroma curry', quantity: '1', unit: 'tbsp', item: 'curry in polvere', note: null, originalText: '1 tbsp curry powder' },
      { group: 'Aroma curry', quantity: '1', unit: 'tbsp', item: 'curcuma in polvere', note: null, originalText: '1 tbsp turmeric powder' },
      { group: 'Aroma tandoori', quantity: '2', unit: 'tbsp', item: 'mix di spezie tandoori', note: null, originalText: '2 tbsp tandoori spice mix' },
      { group: 'Popcorn toffee', quantity: '450', unit: 'g', item: 'zucchero semolato non raffinato', note: null, originalText: '450 g unrefined caster sugar' },
      { group: 'Popcorn toffee', quantity: '250', unit: 'g', item: 'olio di arachide o vinaccioli', note: null, originalText: '250 g groundnut or grapeseed oil' },
      { group: 'Popcorn toffee', quantity: '1', unit: 'tsp', item: 'sale', note: null, originalText: '1 tsp salt' },
      { group: 'Popcorn toffee', quantity: '1/2', unit: 'tsp', item: 'bicarbonato di sodio', note: 'non eccedere per non alterare colore e sapore', originalText: '1/2 tsp bicarbonate of soda' },
      { group: 'Popcorn toffee', quantity: '250', unit: 'g', item: 'mais per popcorn', note: null, originalText: '250 g popcorn kernels' },
    ],
    steps: [
      { section: 'Popcorn aromatizzato', title: 'Scaldare olio e zucchero', text: 'Scalda olio e zucchero in una casseruola grande a fuoco medio-alto fino a raggiungere 150 C.', durationMinutes: null },
      { section: 'Popcorn aromatizzato', title: 'Far scoppiare il mais', text: 'Aggiungi il mais per popcorn e mescola con un cucchiaio di legno per rivestire bene i chicchi con zucchero e olio. Copri con il coperchio: il mais dovrebbe iniziare a scoppiare per circa 2 minuti.', durationMinutes: 2 },
      { section: 'Popcorn aromatizzato', title: 'Finire e condire', text: 'Quando gli scoppi rallentano, togli la pentola dal fuoco e lascia riposare finche smettono completamente. Versa i popcorn in una ciotola, cospargi subito con il mix di spezie scelto e mescola con posate da insalata per distribuire il condimento.', durationMinutes: null },
      { section: 'Aromi', title: 'Cannella', text: 'Per l aroma alla cannella mescola cannella macinata e zucchero semolato, poi usalo sui popcorn ancora caldi e appiccicosi.', durationMinutes: null },
      { section: 'Aromi', title: 'Curry o tandoori', text: 'Per l aroma curry usa curry e curcuma. Per l aroma tandoori usa il mix tandoori. Puoi sostituire con altri aromi a piacere.', durationMinutes: null },
      { section: 'Popcorn toffee', title: 'Caramellare lo zucchero', text: 'Metti lo zucchero in una casseruola grande a fuoco medio-alto. Non toccarlo finche inizia a fondere, poi mescola delicatamente lo zucchero fuso e quello non ancora fuso. Con un pennello bagnato pulisci le pareti della pentola per evitare cristallizzazioni.', durationMinutes: null },
      { section: 'Popcorn toffee', title: 'Aggiungere olio e bicarbonato', text: 'Quando tutto lo zucchero e sciolto, aggiungi l olio e mescola per amalgamare. Unisci sale e bicarbonato: il bicarbonato alleggerisce la struttura del caramello, ma troppo puo alterare colore e sapore.', durationMinutes: null },
      { section: 'Popcorn toffee', title: 'Far scoppiare e raffreddare', text: 'Quando il caramello inizia a bollire, aggiungi il mais e copri. I chicchi scoppieranno per circa 2 minuti. Quando smettono, togli dal fuoco, versa in una ciotola e lascia raffreddare prima di servire.', durationMinutes: 2 },
    ],
    classification: {
      dishType: ['snack', 'dolce'],
      complexity: 'medium',
      mainIngredients: ['mais per popcorn', 'zucchero', 'spezie'],
      season: ['tutto l anno'],
      dietary: ['vegetariano', 'vegano'],
      tags: ['snack', 'caramello', 'spezie', 'google keep', 'ricette'],
      cuisine: ['britannica'],
    },
    personal: {
      rating: null,
      comments: [],
      cookedSessions: [],
      statusTags: ['to try'],
    },
    notes: [
      'Importata manualmente dalla nota Google Keep con label Ricette.',
      'La nota contiene due ricette correlate: popcorn aromatizzato e popcorn toffee.',
    ],
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(flavouredPopcornKeepNote),
      variations: null,
    },
  }),
  keepRecipe({
    id: 'keep-marble-cake-marmor-kuchen',
    title: 'Marble cake - Marmor Kuchen',
    description: 'Cake marmorizzato morbido con burro, latte, yogurt, panna e cacao, cotto in stampo da plumcake.',
    source: {
      type: 'import',
      name: 'Google Keep: Marble cake - marmor kuchen',
      url: null,
      author: null,
      publishedAt: null,
      accessedAt: '2026-05-08T00:00:00.000Z',
    },
    servings: { quantity: 1, unit: 'stampo 27x10 cm', note: null },
    times: { prepMinutes: 25, cookMinutes: 55, restMinutes: 30, totalMinutes: 110 },
    ingredients: [
      { group: null, quantity: '100', unit: 'g', item: 'burro morbido', note: null, originalText: '100 g softened butter' },
      { group: null, quantity: '150', unit: 'g', item: 'zucchero di canna chiaro', note: null, originalText: '150 g light brown sugar' },
      { group: null, quantity: '3', unit: null, item: 'uova grandi', note: 'a temperatura ambiente', originalText: '3 large eggs at room temperature' },
      { group: null, quantity: '150', unit: 'g', item: 'latte intero o parzialmente scremato', note: null, originalText: '150 g whole milk or semi-skimmed' },
      { group: null, quantity: '50', unit: 'g', item: 'yogurt', note: null, originalText: '50 g yogurt' },
      { group: null, quantity: '1', unit: 'bustina', item: 'vaniglia', note: null, originalText: '1 bustina vaniglia' },
      { group: null, quantity: '50', unit: 'g', item: 'olio neutro', note: 'girasole, colza o simile', originalText: '50 g neutral oil type sunflower, rapeseed' },
      { group: null, quantity: '100', unit: 'g', item: 'panna da montare al 30%', note: null, originalText: '100 g heavy whipping cream 30%' },
      { group: null, quantity: '230', unit: 'g', item: 'farina 00', note: null, originalText: '230 g all-purpose flour' },
      { group: null, quantity: '40', unit: 'g', item: 'maizena', note: null, originalText: '40 g maizena' },
      { group: null, quantity: '2', unit: 'cc', item: 'lievito per dolci', note: null, originalText: '2 cc baking powder' },
      { group: null, quantity: '0,5', unit: 'cc', item: 'sale', note: null, originalText: '0,5 cc salt' },
      { group: null, quantity: '26', unit: 'g', item: 'cacao amaro in polvere', note: null, originalText: '26 g unsweetened cocoa powder' },
    ],
    steps: [
      { section: null, title: 'Preparare forno e stampo', text: 'Preriscalda il forno statico a 175 C. Imburra uno stampo da cake e foderalo con carta forno; la nota usa uno stampo da 27x10 cm.', durationMinutes: 10 },
      { section: null, title: 'Montare burro e zucchero', text: 'In un contenitore grande lavora il burro morbido con lo zucchero fino a ottenere una consistenza cremosa. Aggiungi le uova e mescola per rendere omogeneo il composto.', durationMinutes: 8 },
      { section: null, title: 'Preparare secchi e liquidi', text: 'In una ciotola separata mescola farina, maizena, lievito e sale. In un altra ciotola mescola latte, yogurt, olio, panna e vaniglia.', durationMinutes: 5 },
      { section: null, title: 'Completare l impasto', text: 'Aggiungi al composto grande meta dei liquidi, poi meta degli ingredienti secchi. Finisci con il resto dei liquidi e il resto dei secchi. Mescola solo quanto basta, senza lavorare troppo l impasto, per mantenere morbido il cake.', durationMinutes: 5 },
      { section: null, title: 'Creare la parte al cacao', text: 'Dividi l impasto in due parti uguali in due contenitori. In una parte incorpora il cacao amaro setacciato e mescola.', durationMinutes: 4 },
      { section: null, title: 'Marmorizzare nello stampo', text: 'Per creare l effetto marmorizzato versa prima un terzo dell impasto chiaro, poi meta dell impasto al cioccolato. Aggiungi un altro terzo di impasto chiaro, poi l ultima meta di impasto al cioccolato. Termina con l impasto chiaro rimasto.', durationMinutes: 5 },
      { section: null, title: 'Cuocere', text: 'Cuoci per circa 45-55 minuti, regolando in base al forno. La superficie deve essere dorata. Verifica con uno stecchino: deve uscire asciutto o con poche briciole.', durationMinutes: 55 },
      { section: null, title: 'Raffreddare', text: 'Lascia raffreddare, poi sforma il cake su una gratella.', durationMinutes: 30 },
    ],
    classification: {
      dishType: ['dolce', 'cake'],
      complexity: 'easy',
      mainIngredients: ['burro', 'uova', 'latte', 'farina', 'cacao'],
      season: ['tutto l anno'],
      dietary: ['vegetariano'],
      tags: ['forno', 'merenda', 'cake', 'google keep', 'ricette'],
      cuisine: ['tedesca', 'francese'],
    },
    personal: {
      rating: null,
      comments: [],
      cookedSessions: [],
      statusTags: ['to try'],
    },
    notes: ['Importata manualmente dalla nota Google Keep con label Ricette.'],
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(marbleCakeKeepNote),
      variations: null,
    },
  }),
  keepRecipe({
    id: 'keep-gypsy-tart-fallow',
    title: 'Gypsy Tart di Fallow',
    description: 'Crostata britannica con guscio di frolla cotto alla cieca e crema caramellata ricca, cotta lentamente fino a una consistenza appena tremolante.',
    source: {
      type: 'import',
      name: 'Google Keep: Gypsy Tart Fallow',
      url: 'https://www.youtube.com/shorts/1PEiU1hl-nE',
      author: null,
      publishedAt: null,
      accessedAt: '2026-05-08T00:00:00.000Z',
    },
    servings: { quantity: null, unit: 'porzioni', note: null },
    times: { prepMinutes: 120, cookMinutes: 205, restMinutes: 180, totalMinutes: 505 },
    ingredients: [
      { group: 'Pasta frolla', quantity: '216', unit: 'g', item: 'burro non salato', note: 'a cubetti e morbido', originalText: '216 g unsalted butter, cubed and soft' },
      { group: 'Pasta frolla', quantity: '30', unit: 'g', item: 'zucchero semolato bianco', note: null, originalText: '30 g white caster sugar' },
      { group: 'Pasta frolla', quantity: '1', unit: null, item: 'uovo', note: 'sbattuto', originalText: '1 whole egg, beaten' },
      { group: 'Pasta frolla', quantity: '1/2', unit: 'tsp', item: 'latte intero', note: null, originalText: '1/2 tsp whole milk' },
      { group: 'Pasta frolla', quantity: '300', unit: 'g', item: 'farina T55', note: null, originalText: '300 g T55 flour' },
      { group: 'Crema caramellata', quantity: '1100', unit: 'g', item: 'panna fresca', note: null, originalText: '1100 g double cream' },
      { group: 'Crema caramellata', quantity: '270', unit: 'g', item: 'tuorli', note: null, originalText: '270 g egg yolks' },
      { group: 'Crema caramellata', quantity: '100', unit: 'g', item: 'zucchero semolato bianco', note: 'da montare con i tuorli', originalText: '100 g white caster sugar' },
      { group: 'Crema caramellata', quantity: '50', unit: 'g', item: 'zucchero muscovado', note: null, originalText: '50 g muscovado' },
      { group: 'Crema caramellata', quantity: '250', unit: 'g', item: 'zucchero semolato bianco', note: 'per il caramello', originalText: '250 g white caster sugar' },
      { group: 'Crema caramellata', quantity: '12.5', unit: 'g', item: 'sale Maldon', note: null, originalText: '12.5 g Maldon salt' },
    ],
    steps: [
      { section: 'Pasta frolla', title: 'Ammorbidire burro e zucchero', text: 'Metti il burro nella ciotola della planetaria con la foglia e lavoralo a bassa velocita finche diventa morbido. Aggiungi zucchero e latte e continua a mescolare finche sono incorporati.', durationMinutes: null },
      { section: 'Pasta frolla', title: 'Aggiungere uovo e farina', text: 'Raschiare i bordi della ciotola, poi aggiungi gradualmente l uovo sbattuto, aspettando che ogni aggiunta sia incorporata. Sempre a bassa velocita, aggiungi la farina poco alla volta fino a ottenere un impasto omogeneo.', durationMinutes: null },
      { section: 'Pasta frolla', title: 'Riposo', text: 'Togli l impasto dalla ciotola, forma un disco, avvolgilo stretto e lascialo riposare in frigorifero per una o due ore.', durationMinutes: 120 },
      { section: 'Pasta frolla', title: 'Stendere', text: 'Togli la pasta dal frigo e lasciala temperare a temperatura ambiente. Stendila su carta forno a 0,5 cm di spessore, abbastanza larga da coprire lo stampo con un bordo abbondante.', durationMinutes: null },
      { section: 'Cottura alla cieca', title: 'Foderare lo stampo', text: 'Ungi leggermente l interno dello stampo, metti un quadrato di carta forno sulla base e fodera lo stampo premendo la pasta nelle scanalature.', durationMinutes: null },
      { section: 'Cottura alla cieca', title: 'Prima cottura con pesi', text: 'Copri la pasta con pellicola resistente alla cottura, aggiungi un tovagliolo o carta, riempi con riso da cottura alla cieca e premi bene sui bordi. Aggiungi qualche peso metallico se serve. Cuoci a 150 C con 100% umidita e ventola 4 per 50 minuti, cercando una colorazione dorata chiara e uniforme.', durationMinutes: 50 },
      { section: 'Cottura alla cieca', title: 'Asciugare il guscio', text: 'Rimuovi il riso, ripara eventuali crepe con ritagli di pasta e continua la cottura a 150 C con 0% umidita e ventola 3 per 10-15 minuti, finche anche il centro e cotto.', durationMinutes: 15 },
      { section: 'Cottura alla cieca', title: 'Spennellare', text: 'Quando il guscio e ancora caldo, spennellalo con tuorlo e cuoci a 90 C con 0% umidita e ventola 2 per 10 minuti.', durationMinutes: 10 },
      { section: 'Crema caramellata', title: 'Scaldare panna e tuorli', text: 'Scalda dolcemente la panna in una pentola grande. In una ciotola capiente sbatti leggermente i tuorli con 100 g di zucchero semolato e lo zucchero muscovado.', durationMinutes: null },
      { section: 'Crema caramellata', title: 'Fare il caramello', text: 'Metti 100 ml di acqua in un pentolino, poi a fuoco medio versa a pioggia i 250 g di zucchero semolato mescolando per scioglierlo. Alza il calore e fai bollire fino a ottenere un caramello scuro.', durationMinutes: null },
      { section: 'Crema caramellata', title: 'Unire panna e uova', text: 'Quando il caramello ha il colore desiderato, versa con cautela la panna calda poco alla volta: bollira e schizzerera, quindi resta indietro e procedi piano. Mescola fino a ottenere una salsa liscia, poi fuori dal fuoco versala sul composto di uova continuando a frustare. Aggiungi il sale e amalgama.', durationMinutes: null },
      { section: 'Assemblaggio', title: 'Riempire e cuocere', text: 'Versa la crema nel guscio gia precotto mentre il guscio e nel forno, cosi eviti fuoriuscite e puoi riempire fino al bordo. Cuoci a 95 C per 2 ore, poi controlla il tremolio: deve essere morbido ma senza increspature. Aggiungi tempo se necessario.', durationMinutes: 120 },
      { section: 'Servizio', title: 'Raffreddare e tagliare', text: 'Lascia raffreddare a temperatura ambiente per 1 ora, poi metti in frigo per almeno 2 ore prima di affettare. Taglia con un coltello affilato e servi con poco sale Maldon e una cucchiaiata di creme fraiche.', durationMinutes: 180 },
    ],
    classification: {
      dishType: ['dolce', 'crostata'],
      complexity: 'hard',
      mainIngredients: ['panna', 'tuorli', 'zucchero', 'burro', 'farina'],
      season: ['tutto l anno'],
      dietary: ['vegetariano'],
      tags: ['forno', 'da preparare in anticipo', 'google keep', 'ricette', 'to try'],
      cuisine: ['britannica'],
    },
    personal: {
      rating: null,
      comments: [],
      cookedSessions: [],
      statusTags: ['to try'],
    },
    notes: [
      'Importata dalla nota Google Keep con label Ricette.',
      'Le impostazioni con percentuale di umidita e ventola vengono dalla ricetta originale; in forno domestico vanno adattate.',
    ],
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(gypsyTartKeepNote),
      variations: null,
    },
  }),
  keepRecipe({
    id: 'keep-focaccia-genovese-davide-zambelli',
    title: 'Focaccia Genovese Davide Zambelli',
    description: 'Focaccia genovese in teglia 30x40 cm con salamoia, lunga lievitazione e cottura molto calda.',
    source: {
      type: 'import',
      name: 'Google Keep: Focaccia Genovese Davide Zambelli',
      url: 'https://www.davidezambelli.com/ricette/focaccia-genovese-fatta-in-casa/',
      author: 'Davide Zambelli',
      publishedAt: null,
      accessedAt: '2026-05-08T00:00:00.000Z',
    },
    servings: { quantity: 1, unit: 'teglia 30x40 cm', note: null },
    times: { prepMinutes: 35, cookMinutes: 10, restMinutes: 230, totalMinutes: 275 },
    ingredients: [
      { group: 'Impasto', quantity: '400', unit: 'g', item: 'farina tipo 1 o 0', note: null, originalText: '400 g farina di tipo 1 o 0' },
      { group: 'Impasto', quantity: '220', unit: 'ml', item: 'acqua tiepida', note: 'tenerne da parte 10 ml', originalText: '220 ml acqua tiepida' },
      { group: 'Impasto', quantity: '8', unit: 'g', item: 'lievito di birra fresco', note: null, originalText: '8 g lievito di birra fresco' },
      { group: 'Impasto', quantity: '10', unit: 'g', item: 'sale', note: null, originalText: '10 g sale' },
      { group: 'Impasto', quantity: '30', unit: 'g', item: 'olio extravergine di oliva', note: '15 g + 15 g', originalText: '30 g olio extravergine di oliva' },
      { group: 'Impasto', quantity: '1', unit: 'cucchiaino', item: 'malto, miele o zucchero', note: null, originalText: '1 cucchiaino di malto, miele o zucchero' },
      { group: 'Salamoia', quantity: '50', unit: 'ml', item: 'acqua', note: null, originalText: '50 ml acqua' },
      { group: 'Salamoia', quantity: '25', unit: 'ml', item: 'olio extravergine di oliva', note: null, originalText: '25 ml olio extravergine di oliva' },
      { group: 'Salamoia', quantity: '4', unit: 'g', item: 'sale', note: null, originalText: '4 g sale' },
      { group: 'Salamoia', quantity: null, unit: null, item: 'sale grosso', note: 'qualche chicco', originalText: 'qualche chicco di sale grosso' },
    ],
    steps: [
      { section: 'Impasto', title: 'Preparare la fontana', text: 'Versa la farina a fontana, aggiungi quasi tutta l’acqua, il lievito e il miele, poi incorpora fino a ottenere un impasto grezzo.', durationMinutes: 10 },
      { section: 'Impasto', title: 'Aggiungere sale e olio', text: 'Aggiungi sale e acqua rimanente, impasta circa 8 minuti. Incorpora l’olio in due volte e impasta altri 2 minuti.', durationMinutes: 10 },
      { section: 'Lievitazione', title: 'Pieghe e prima lievitazione', text: 'Copri 15 minuti, poi fai due pieghe, forma una palla e lascia lievitare coperto per 1 ora e mezza.', durationMinutes: 105 },
      { section: 'Stesura', title: 'Stendere in teglia', text: 'Stendi con il mattarello, trasferisci nella teglia unta e fai riposare 30 minuti.', durationMinutes: 30 },
      { section: 'Stesura', title: 'Seconda stesura', text: 'Stendi con le mani senza arrivare ai bordi, riposa 30 minuti, poi stendi fino ai bordi e riposa altri 10 minuti.', durationMinutes: 70 },
      { section: 'Cottura', title: 'Salamoia e forno', text: 'Emulsiona acqua, olio e sale. Versa sulla focaccia, fai i buchi, riposa 1 ora e cuoci a 250-260 °C statico per circa 10 minuti.', durationMinutes: 70 },
      { section: 'Cottura', title: 'Raffreddare', text: 'Sforna e trasferisci subito su una gratella.', durationMinutes: null },
    ],
    classification: {
      dishType: ['bread', 'side'],
      complexity: 'medium',
      mainIngredients: ['farina', 'olio extravergine di oliva', 'lievito'],
      season: ['all season'],
      dietary: ['vegetarian'],
      tags: ['focaccia', 'lievitati', 'google keep', 'ricette'],
      cuisine: ['ligurian', 'italian'],
    },
    notes: ['Importata dalla nota Google Keep con label Ricette.'],
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(focacciaKeepNote),
      variations: null,
    },
  }),
  keepRecipe({
    id: 'keep-farinata',
    title: 'Farinata',
    description: 'Farinata di ceci con proporzioni per testi di diverse dimensioni e cottura molto calda sotto grill.',
    source: { type: 'import', name: 'Google Keep: Farinata', url: null, author: null, publishedAt: null, accessedAt: '2026-05-08T00:00:00.000Z' },
    servings: { quantity: 1, unit: 'testo 40 cm', note: null },
    times: { prepMinutes: 10, cookMinutes: 13, restMinutes: 240, totalMinutes: 263 },
    ingredients: [
      { group: null, quantity: '200', unit: 'g', item: 'farina di ceci', note: null, originalText: '200 farina' },
      { group: null, quantity: '600', unit: 'g', item: 'acqua', note: null, originalText: '600 acqua' },
      { group: null, quantity: '8', unit: 'g', item: 'sale', note: null, originalText: '8 sale' },
      { group: null, quantity: '75', unit: 'g', item: 'olio', note: 'circa 1 dl per testo 40 cm', originalText: '75 olio' },
    ],
    steps: [
      { section: null, title: 'Preparare la pastella', text: 'Mescola farina di ceci, acqua e sale fino a ottenere una pastella liscia.', durationMinutes: 10 },
      { section: null, title: 'Riposo', text: 'Lascia riposare almeno 4 ore.', durationMinutes: 240 },
      { section: null, title: 'Scaldare il testo', text: 'Porta il forno a 220 °C e scalda il testo per un paio di minuti.', durationMinutes: 2 },
      { section: null, title: 'Cottura iniziale', text: 'Imposta grill a 300 °C, versa l’olio nel testo, aggiungi la pastella, mescola e inforna.', durationMinutes: 5 },
      { section: null, title: 'Gestire il calore', text: 'Quando inizia a friggere abbassa a 275 °C. Scuoti il testo quando comincia a rapprendersi.', durationMinutes: 4 },
      { section: null, title: 'Finale', text: 'Quando mancano 4 minuti riporta il forno a 300 °C. Tempo totale indicativo 12-13 minuti.', durationMinutes: 4 },
    ],
    classification: {
      dishType: ['side', 'snack'],
      complexity: 'easy',
      mainIngredients: ['farina di ceci', 'olio'],
      season: ['all season'],
      dietary: ['vegetarian', 'vegan'],
      tags: ['liguria', 'testo', 'google keep', 'ricette'],
      cuisine: ['ligurian', 'italian'],
    },
    notes: ['La nota contiene anche una tabella di dosi per testi da 30 a 90 cm.'],
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(farinataKeepNote),
      variations: null,
    },
  }),
  keepRecipe({
    id: 'keep-pastel-de-nata',
    title: 'Pastel de Nata',
    description: 'Pasteis de nata con crema al latte, cannella e limone, cotti ad alta temperatura.',
    source: { type: 'import', name: 'Google Keep: Pastel de Nata', url: null, author: null, publishedAt: null, accessedAt: '2026-05-08T00:00:00.000Z' },
    servings: { quantity: 12, unit: 'pasteis', note: 'la nota dice 10-12, fino a 15 se la pasta è molto sottile' },
    times: { prepMinutes: 45, cookMinutes: 12, restMinutes: 20, totalMinutes: 77 },
    ingredients: [
      { group: 'Crema', quantity: '250', unit: 'g', item: 'latte', note: null, originalText: '250 gr of milk' },
      { group: 'Crema', quantity: '150', unit: 'g', item: 'zucchero', note: null, originalText: '150 gr of sugar' },
      { group: 'Crema', quantity: '75', unit: 'g', item: 'acqua', note: null, originalText: '75 gr water' },
      { group: 'Crema', quantity: '30', unit: 'g', item: 'farina per dolci', note: 'senza lievito', originalText: '30 gr of flour' },
      { group: 'Crema', quantity: '4', unit: null, item: 'tuorli', note: null, originalText: '4 egg yolks' },
      { group: 'Aromi', quantity: '1-2', unit: null, item: 'stecche di cannella', note: null, originalText: '1 or 2 cinnamon sticks' },
      { group: 'Aromi', quantity: '3-4', unit: null, item: 'scorze di limone', note: null, originalText: '3 or 4 lemon peels' },
      { group: 'Base', quantity: '300', unit: 'g', item: 'pasta sfoglia', note: 'preferibilmente fatta in casa', originalText: 'About 300gr of custard dough' },
      { group: 'Finitura', quantity: null, unit: null, item: 'cannella in polvere', note: 'opzionale ma consigliata', originalText: 'Cinnamon Powder' },
      { group: 'Finitura', quantity: null, unit: null, item: 'zucchero a velo', note: 'opzionale', originalText: 'Powdered Sugar' },
    ],
    steps: [
      { section: 'Crema', title: 'Sciroppo', text: 'Porta acqua e zucchero a bollore senza mescolare durante la bollitura. Fai bollire fino al punto perlato, circa 3 minuti.', durationMinutes: 3 },
      { section: 'Crema', title: 'Latte e farina', text: 'Sciogli la farina in poco latte freddo. Porta il resto del latte a bollore con cannella e limone.', durationMinutes: 8 },
      { section: 'Crema', title: 'Addensare', text: 'Fuori dal fuoco incorpora il composto di farina poco per volta, poi rimetti sul fuoco e mescola finché diventa cremoso.', durationMinutes: 8 },
      { section: 'Crema', title: 'Unire lo sciroppo', text: 'Aggiungi lo sciroppo lentamente mescolando con la frusta. Lascia raffreddare circa 10 minuti.', durationMinutes: 10 },
      { section: 'Crema', title: 'Tuorli', text: 'Stempera i tuorli con poca crema, poi unisci il composto alla crema. Elimina cannella e limone.', durationMinutes: 6 },
      { section: 'Formatura', title: 'Pasta', text: 'Stendi la pasta in rettangolo, arrotola a cilindro e taglia dischi spessi circa 2 cm.', durationMinutes: 10 },
      { section: 'Formatura', title: 'Stampi', text: 'Sistema i dischi negli stampi imburrati e modella con il pollice bagnato. Raffredda 10 minuti.', durationMinutes: 10 },
      { section: 'Cottura', title: 'Riempire e cuocere', text: 'Riempi a tre quarti e cuoci in forno molto caldo a 250 °C o al massimo disponibile per 10-12 minuti, finché la superficie scurisce.', durationMinutes: 12 },
    ],
    classification: {
      dishType: ['dessert', 'pastry'],
      complexity: 'medium',
      mainIngredients: ['latte', 'tuorli', 'pasta sfoglia'],
      season: ['all season'],
      dietary: ['vegetarian'],
      tags: ['portuguese', 'custard tart', 'google keep', 'ricette'],
      cuisine: ['portuguese'],
    },
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(pastelKeepNote),
      variations: null,
    },
  }),
  keepRecipe({
    id: 'keep-sbrisolona',
    title: 'Sbrisolona',
    description: 'Torta rustica mantovana alle mandorle, da rompere con le mani.',
    source: { type: 'import', name: 'Google Keep: Sbrisolona', url: 'https://youtu.be/yPLMpYMvGxE?si=ghf4X43tq4BDgPdS', author: null, publishedAt: null, accessedAt: '2026-05-08T00:00:00.000Z' },
    servings: { quantity: 1, unit: 'torta 24 cm', note: 'la nota include anche dosi Massari per stampo più grande' },
    times: { prepMinutes: 20, cookMinutes: 50, restMinutes: 20, totalMinutes: 90 },
    ingredients: [
      { group: null, quantity: '200', unit: 'g', item: 'mandorle pelate', note: 'tritate grossolanamente', originalText: '200 g blanched almonds' },
      { group: null, quantity: '200', unit: 'g', item: 'farina di mais fioretto', note: null, originalText: '200 g fine corn flour' },
      { group: null, quantity: '200', unit: 'g', item: 'farina 00', note: 'oppure tipo 1 o 0', originalText: '200 g 00 flour' },
      { group: null, quantity: '200', unit: 'g', item: 'zucchero semolato', note: null, originalText: '200 g granulated sugar' },
      { group: null, quantity: '200', unit: 'g', item: 'burro', note: 'morbido ma plastico', originalText: '200 g butter' },
      { group: null, quantity: '2', unit: null, item: 'tuorli', note: null, originalText: '2 egg yolks' },
      { group: null, quantity: null, unit: null, item: 'vaniglia', note: 'a piacere', originalText: 'Vanilla flavoring to taste' },
      { group: null, quantity: '1/2', unit: null, item: 'scorza di limone', note: null, originalText: 'Zest of half a lemon' },
      { group: null, quantity: '1', unit: 'pizzico', item: 'sale', note: null, originalText: '1 pinch of salt' },
      { group: null, quantity: null, unit: null, item: 'mandorle non pelate', note: 'per la superficie', originalText: 'A handful of unpeeled almonds' },
    ],
    steps: [
      { section: null, title: 'Tritare le mandorle', text: 'Trita grossolanamente le mandorle pelate senza ridurle in farina.', durationMinutes: 5 },
      { section: null, title: 'Miscelare le polveri', text: 'In una ciotola grande mescola farina 00, farina di mais, zucchero e mandorle tritate.', durationMinutes: 2 },
      { section: null, title: 'Sabbiare', text: 'Aggiungi il burro a cubetti morbido e sbriciolalo con le dita nel mix di farine.', durationMinutes: 6 },
      { section: null, title: 'Completare impasto', text: 'Aggiungi scorza di limone, vaniglia, sale e tuorli. Continua a sbriciolare fino a ottenere un composto umido, sabbioso e irregolare.', durationMinutes: 7 },
      { section: null, title: 'Formare', text: 'Versa in teglia in due strati, premendo appena senza compattare troppo. Aggiungi mandorle non pelate e poco zucchero.', durationMinutes: 5 },
      { section: null, title: 'Cuocere', text: 'Cuoci al centro del forno ventilato a 180 °C per circa 50 minuti, finché dorata e asciutta.', durationMinutes: 50 },
      { section: null, title: 'Servire', text: 'Lascia raffreddare almeno 20 minuti e rompi con le mani invece di tagliare.', durationMinutes: 20 },
    ],
    classification: {
      dishType: ['dessert', 'cake'],
      complexity: 'easy',
      mainIngredients: ['mandorle', 'farina di mais', 'burro'],
      season: ['all season'],
      dietary: ['vegetarian'],
      tags: ['mantova', 'baking', 'google keep', 'ricette'],
      cuisine: ['italian', 'mantuan'],
    },
    notes: ['La nota cita anche Massari/Giallo Zafferano e una versione Rapanello.'],
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(sbrisolonaKeepNote),
      variations: null,
    },
  }),
  keepRecipe({
    id: 'keep-crescenza-dal-thread-del-forum',
    title: 'Crescenza dal thread del forum',
    description: 'Crescenza domestica da 2 litri di latte, con panna, yogurt, caglio, stufatura umida e maturazione breve.',
    source: {
      type: 'import',
      name: 'Google Keep: Crescenza Dal Thread Del Forum',
      url: 'https://produzioneformaggi.forumfree.it/',
      author: null,
      publishedAt: null,
      accessedAt: '2026-05-08T00:00:00.000Z',
    },
    servings: { quantity: 425, unit: 'g circa', note: 'resa indicativa da 2 L di latte' },
    times: { prepMinutes: 80, cookMinutes: null, restMinutes: 5940, totalMinutes: 6020 },
    ingredients: [
      { group: null, quantity: '2', unit: 'L', item: 'latte vaccino', note: null, originalText: '2 L latte' },
      { group: null, quantity: '80', unit: 'g', item: 'panna al 36%', note: null, originalText: '80 g panna al 36%' },
      { group: null, quantity: '50', unit: 'g', item: 'yogurt', note: 'starter termofilo', originalText: '50 g yogurt' },
      { group: null, quantity: '1,2', unit: 'ml', item: 'caglio liquido di vitello 1:10000', note: '0,6 ml/L', originalText: '1,2 ml totali per 2 litri' },
      { group: null, quantity: '18', unit: 'g', item: 'sale', note: '9 g per faccia, alternativa 7-8 g/L in pasta', originalText: '9 g per faccia' },
    ],
    steps: [
      { section: 'Latte', title: 'Pastorizzare', text: 'Porta il latte vaccino a 72 °C, aggiungi la panna, mescola 2 minuti e raffredda a 39 °C.', durationMinutes: 20 },
      { section: 'Starter', title: 'Aggiungere yogurt', text: 'Aggiungi lo yogurt, mescola 2 minuti e attendi 15 minuti.', durationMinutes: 17 },
      { section: 'Caglio', title: 'Coagulare', text: 'Aggiungi il caglio, mescola 1 minuto, copri e attendi 60 minuti.', durationMinutes: 61 },
      { section: 'Cagliata', title: 'Taglio', text: 'Taglia la cagliata a cubi di circa 2 x 2 cm, copri e attendi 25 minuti.', durationMinutes: 25 },
      { section: 'Cagliata', title: 'Rivoltare nel siero', text: 'Capovolgi delicatamente i cubetti dal basso verso l’alto, poi copri e attendi 50 minuti.', durationMinutes: 50 },
      { section: 'Fuscella', title: 'Messa in forma', text: 'Preleva delicatamente i pezzi con una schiumarola e mettili in fuscella.', durationMinutes: 10 },
      { section: 'Stufatura', title: 'Stufare e rivoltare', text: 'Stufa 3 ore a 25 °C e 90% U.R., rivoltando spesso secondo il programma della nota.', durationMinutes: 180 },
      { section: 'Salatura', title: 'Salare', text: 'Togli dalla fuscella, sala a secco 9 g per faccia e rimetti in fuscella.', durationMinutes: 10 },
      { section: 'Maturazione', title: 'Frigo', text: 'Matura in frigo a circa 10 °C e alta umidità, rivoltando ogni 12 ore. Assaggia dopo 4 giorni.', durationMinutes: 5760 },
    ],
    classification: {
      dishType: ['cheese'],
      complexity: 'hard',
      mainIngredients: ['latte', 'panna', 'yogurt', 'caglio'],
      season: ['all season'],
      dietary: ['vegetarian'],
      tags: ['formaggio', 'crescenza', 'google keep', 'ricette'],
      cuisine: ['italian'],
    },
    notes: [
      'La nota originale contiene troubleshooting su durezza, crosta, acidità e umidità.',
      'Importazione di prova da Google Keep label Ricette.',
    ],
    markdown: {
      intro: 'Testo originale integrale dalla nota Google Keep.',
      methodNotes: originalKeepText(crescenzaKeepNote),
      variations: null,
    },
  }),
];
